server:
  http_port: 8082
  grpc_port: 8083

database:
  host: localhost
  port: 5432
  name: algotrading
  user: postgres
  password: password123

redis:
  host: localhost
  port: 6379

market_data_service:
  grpc_address: localhost:8081

risk_management:
  max_position_size: 100000
  max_daily_loss: 50000
  max_positions: 10

strategies:
  - name: "momentum_strategy"
    enabled: false
    parameters:
      rsi_period: 14
      rsi_oversold: 30
      rsi_overbought: 70

